### ISSUE TITLE
Read secrets from a file

### ISSUE THREAD

**Issue by happysalada** [tremor-rs/tremor-runtime#2071] opened 2022-11-14 15:06 UTC
Rather than putting secrets in clean text in our troy file, there should.be a way to read secrets from a file. An example of this would be the password in the http basic auth, or an api key in the headers... 
An additional benefit is that this would allow troy files to be commited to a versiom control system (git...). Commiting secrets to a repo is not a great idea.

**Describe the solution you'd like**
A function like readFromFile would be amazing

**Notes**

If this is an implementation of an [RFC](https://github.com/tremor-rs/tremor-rfcs) provide a URL
to the RFC this enhancement implements.

If this is a major enhancement or contribution an RFC may be required. It is ok to submit an enhancement
first and our core team will assist with major contributions. In general, major contributions should be
discussed with the community before submission.

**Comment by happysalada** [comment] 2022-11-14 16:48
Thank you !

**Comment by Licenser** [comment] 2022-11-15 09:44
good catch and glad the original issue help you happysalada!

closing as  duplicate of #1580

**Closed by Licenser** 2022-11-15 09:44 UTC
Labels: duplicate, enhancement
