### ISSUE TITLE
Replace current elasticsearch client with the official one

### ISSUE THREAD

**Issue by SpyrosRoum** [tremor-rs/tremor-runtime#832] opened 2021-03-12 11:12 UTC
**Describe the problem you are trying to solve**
Replacing the current elasticsearch client used with the official one may have performance implication

**Describe the solution you'd like**
Use the official client for elasticsearch, see #411 as well

**Notes**
The official client doesn't support connection pooling yet but there is an open pr that seems to be close to completion: elastic/elasticsearch-rs#139

**Comment by Licenser** [comment] 2022-08-10 08:29
duplicate of https://github.com/tremor-rs/tremor-runtime/issues/411

**Closed by Licenser** 2022-08-10 08:29 UTC
Labels: duplicate, enhancement, _complexity:low, _size:medium
